---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dieterstockhausen.
--- DateTime: 05.05.21 19:19
--[[----------------------------------------------------------------------------
-----------------------------------------------------------------------------]]

local Utils = {}
--[[----------------------------------------------------------------------------
-----------------------------------------------------------------------------]]

function Utils.arraySize(array)
    count = 0
    for _ in pairs(array) do count = count + 1 end
    return count
end
--[[----------------------------------------------------------------------------
-----------------------------------------------------------------------------]]

function Utils.startsWith(str, start)
    return str:sub(1, #start) == start
end
--[[----------------------------------------------------------------------------
-----------------------------------------------------------------------------]]

function Utils.endsWith(str, ending)
    return ending == "" or str:sub(-#ending) == ending
end
--[[----------------------------------------------------------------------------
-----------------------------------------------------------------------------]]
function Utils.copyfile(old_path, new_path)
    local old_file = io.open(old_path, "rb")
    local new_file = io.open(new_path, "wb")
    local old_file_sz, new_file_sz = 0, 0
    if not old_file or not new_file then
        return false
    end
    while true do
        local block = old_file:read(2^13)
        if not block then
            old_file_sz = old_file:seek( "end" )
            break
        end
        new_file:write(block)
    end
    old_file:close()
    new_file_sz = new_file:seek( "end" )
    new_file:close()
    return new_file_sz == old_file_sz
end
--[[----------------------------------------------------------------------------
-----------------------------------------------------------------------------]]
return Utils