---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dieterstockhausen.
--- DateTime: 05.05.21 19:19
local LrFileUtils = import 'LrFileUtils'
local LrPathUtils = import 'LrPathUtils'
local LrApplication = import 'LrApplication'

--[[----------------------------------------------------------------------------
-----------------------------------------------------------------------------]]

local Utils = {}
--[[----------------------------------------------------------------------------
-----------------------------------------------------------------------------]]

function Utils.arraySize(array)
    count = 0
    for _ in pairs(array) do count = count + 1 end
    return count
end
--[[----------------------------------------------------------------------------
-----------------------------------------------------------------------------]]

function Utils.startsWith(str, start)
    return str:sub(1, #start) == start
end
--[[----------------------------------------------------------------------------
-----------------------------------------------------------------------------]]

function Utils.endsWith(str, ending)
    return ending == "" or str:sub(-#ending) == ending
end
--[[----------------------------------------------------------------------------
-----------------------------------------------------------------------------]]
function Utils.copyfile(old_path, new_path)
    local old_file = io.open(old_path, "rb")
    local new_file = io.open(new_path, "wb")
    local old_file_sz, new_file_sz = 0, 0
    if not old_file or not new_file then
        return false
    end
    while true do
        local block = old_file:read(2^13)
        if not block then
            old_file_sz = old_file:seek( "end" )
            break
        end
        new_file:write(block)
    end
    old_file:close()
    new_file_sz = new_file:seek( "end" )
    new_file:close()
    return new_file_sz == old_file_sz
end

--[[----------------------------------------------------------------------------
-----------------------------------------------------------------------------]]
function Utils.trim(s)
    return (s:gsub("^%s*(.-)%s*$", "%1"))
end
--[[----------------------------------------------------------------------------
-----------------------------------------------------------------------------]]

function Utils.getSessionFile(albumPath)
    return LrPathUtils.child(Utils.getComDir(albumPath), "session.txt")
end
--[[----------------------------------------------------------------------------
-----------------------------------------------------------------------------]]
function Utils.getPhotosFile(albumPath)
    return LrPathUtils.child(Utils.getComDir(albumPath), "photos.txt")
end
--[[----------------------------------------------------------------------------
-----------------------------------------------------------------------------]]
function Utils.getComDir(albumPath)
    local comDir = _G.TMP_DIR .. albumPath
    if (not LrFileUtils.exists(comDir)) then
        LrFileUtils.createAllDirectories(comDir)
    end
    return comDir
end
--[[----------------------------------------------------------------------------
-----------------------------------------------------------------------------]]
function Utils.getQueueEntryBaseName()
    return "queue-entry"
end
--[[----------------------------------------------------------------------------
-----------------------------------------------------------------------------]]
function Utils.getQueueDir()
    return _G.QUEUE_DIR
end
--[[----------------------------------------------------------------------------
-----------------------------------------------------------------------------]]
function Utils.getQueueEntry()
    return LrFileUtils.chooseUniqueFileName(LrPathUtils.child( Utils.getQueueEntryDir(), Utils.getQueueEntryBaseName()))
end
--[[----------------------------------------------------------------------------
-----------------------------------------------------------------------------]]
function Utils.getQueueEntry()
    local queueDir = _G.TMP_DIR .. "/queue"
    if (not LrFileUtils.exists(queueDir)) then
        LrFileUtils.createAllDirectories(queueDir)
    end
    return queueDir .. "/queue-entry"
end
--[[----------------------------------------------------------------------------
-----------------------------------------------------------------------------]]
--[[---------------------------------------------------------------------------
getCatName()
-----------------------------------------------------------------------------]]
function Utils.getCatName ()
    local activeCatalog = LrApplication.activeCatalog()
    local catName = LrPathUtils.removeExtension(LrPathUtils.leafName(activeCatalog:getPath()))
    local i = string.find(catName, "-v")
    if (i ~= nil and i > 1) then
        catName = string.sub(catName, 1, i - 1)
    end
    return catName
end
return Utils